10 REM READS TWO NUMBERS AND A NAME. RUN IT AND TYPE, FOR EXAMPLE:  3, 4
20 PRINT "TWO NUMBERS, SEPARATED BY A COMMA";
30 INPUT A, B
40 PRINT "SUM IS"; A + B
50 PRINT "PRODUCT IS"; A * B
60 PRINT "AND YOUR NAME";
70 INPUT N$
80 PRINT "THANK YOU, "; N$
90 END
