10 REM A SINE WAVE. ROADMAP 3.14 SPENT ITS LIFE WAITING FOR A PROGRAM
20 REM THAT WANTED AN ANGLE, AND SAID IT WOULD BE "A PLOTTER, A
30 REM SIMULATION, ANYTHING WITH COORDINATES OR A WAVEFORM".
40 LET P = 4 * ATN(1)
50 FOR I = 0 TO 24
60 LET A = I * P / 6
70 PRINT TAB(21 + 18 * SIN(A)); "*"
80 NEXT I
90 END
