-- Deletes, written by hand: sixty rows on 512-byte pages make three leaves
-- and an index tree of two, and the deletes below empty leaves, take a key
-- out of an interior index cell, and leave the table empty before it fills
-- again from the freelist. `PRAGMA freelist_count` says how many pages are
-- free and `integrity_check` walks the trunk.
PRAGMA page_size = 512;
CREATE TABLE t (n INTEGER, s TEXT, k TEXT);
CREATE INDEX t_k ON t (k);
CREATE INDEX t_s ON t (s);
INSERT INTO t VALUES (1, 'row 1', 'green');
INSERT INTO t VALUES (2, 'row 2', 'blue');
INSERT INTO t VALUES (3, 'row 3', 'red');
INSERT INTO t VALUES (4, 'row 4', 'green');
INSERT INTO t VALUES (5, 'row 5', 'blue');
INSERT INTO t VALUES (6, 'row 6', 'red');
INSERT INTO t VALUES (7, 'row 7', 'green');
INSERT INTO t VALUES (8, 'row 8', 'blue');
INSERT INTO t VALUES (9, 'row 9', 'red');
INSERT INTO t VALUES (10, 'row 10', 'green');
INSERT INTO t VALUES (11, 'row 11', 'blue');
INSERT INTO t VALUES (12, 'row 12', 'red');
INSERT INTO t VALUES (13, 'row 13', 'green');
INSERT INTO t VALUES (14, 'row 14', 'blue');
INSERT INTO t VALUES (15, 'row 15', 'red');
INSERT INTO t VALUES (16, 'row 16', 'green');
INSERT INTO t VALUES (17, 'row 17', 'blue');
INSERT INTO t VALUES (18, 'row 18', 'red');
INSERT INTO t VALUES (19, 'row 19', 'green');
INSERT INTO t VALUES (20, 'row 20', 'blue');
INSERT INTO t VALUES (21, 'row 21', 'red');
INSERT INTO t VALUES (22, 'row 22', 'green');
INSERT INTO t VALUES (23, 'row 23', 'blue');
INSERT INTO t VALUES (24, 'row 24', 'red');
INSERT INTO t VALUES (25, 'row 25', 'green');
INSERT INTO t VALUES (26, 'row 26', 'blue');
INSERT INTO t VALUES (27, 'row 27', 'red');
INSERT INTO t VALUES (28, 'row 28', 'green');
INSERT INTO t VALUES (29, 'row 29', 'blue');
INSERT INTO t VALUES (30, 'row 30', 'red');
INSERT INTO t VALUES (31, 'row 31', 'green');
INSERT INTO t VALUES (32, 'row 32', 'blue');
INSERT INTO t VALUES (33, 'row 33', 'red');
INSERT INTO t VALUES (34, 'row 34', 'green');
INSERT INTO t VALUES (35, 'row 35', 'blue');
INSERT INTO t VALUES (36, 'row 36', 'red');
INSERT INTO t VALUES (37, 'row 37', 'green');
INSERT INTO t VALUES (38, 'row 38', 'blue');
INSERT INTO t VALUES (39, 'row 39', 'red');
INSERT INTO t VALUES (40, 'row 40', 'green');
INSERT INTO t VALUES (41, 'row 41', 'blue');
INSERT INTO t VALUES (42, 'row 42', 'red');
INSERT INTO t VALUES (43, 'row 43', 'green');
INSERT INTO t VALUES (44, 'row 44', 'blue');
INSERT INTO t VALUES (45, 'row 45', 'red');
INSERT INTO t VALUES (46, 'row 46', 'green');
INSERT INTO t VALUES (47, 'row 47', 'blue');
INSERT INTO t VALUES (48, 'row 48', 'red');
INSERT INTO t VALUES (49, 'row 49', 'green');
INSERT INTO t VALUES (50, 'row 50', 'blue');
INSERT INTO t VALUES (51, 'row 51', 'red');
INSERT INTO t VALUES (52, 'row 52', 'green');
INSERT INTO t VALUES (53, 'row 53', 'blue');
INSERT INTO t VALUES (54, 'row 54', 'red');
INSERT INTO t VALUES (55, 'row 55', 'green');
INSERT INTO t VALUES (56, 'row 56', 'blue');
INSERT INTO t VALUES (57, 'row 57', 'red');
INSERT INTO t VALUES (58, 'row 58', 'green');
INSERT INTO t VALUES (59, 'row 59', 'blue');
INSERT INTO t VALUES (60, 'row 60', 'red');
DELETE FROM t WHERE k = 'red';
DELETE FROM t WHERE rowid > 20 AND rowid < 45;
DELETE FROM t WHERE rowid = 1;
DELETE FROM t WHERE s = 'row 59';
INSERT INTO t VALUES (61, 'row 61', 'red');
DELETE FROM t WHERE n >= 50;
DELETE FROM t WHERE k = 'blue';
DELETE FROM t WHERE k = 'green';
INSERT INTO t VALUES (100, 'again', 'red');
-- queries
SELECT rowid, * FROM t ORDER BY rowid;
SELECT rowid FROM t WHERE k = 'red' ORDER BY rowid;
SELECT rowid FROM t WHERE s = 'again';
SELECT type, name, tbl_name FROM sqlite_schema;
